version: "3.8"
services:
  ws:
    container_name: ws_server
    restart: on-failure
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - "8080:8080"
    command: >
      sh -c "node ."
  nginx-react:
    container_name: nginxreactapp
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production