version: "3.8"
services:
  ws:
    container_name: ws_server
    restart: on-failure
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - "8080:8080"
    command: >
      sh -c "node ."

  react-app:
    container_name: react_app
    # restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      NODE_ENV: production
    # volumes:
    #   - ./src:/app/src
    # ports:
    #   - "3000:3000"
    # command: >
    #   sh -c "npm start"
    # depends_on:
    #   - ws
